name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install server dependencies
      run: cd Cambiame/server && npm ci
    - name: Install client dependencies
      run: cd Cambiame/client && npm ci
    - name: Build server
      run: cd Cambiame/server && npm run build --if-present
    - name: Build client
      run: cd Cambiame/client && npm run build --if-present
