name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js adarsh
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install server dependencies
      run: pwd
      working-directory: ./server
    - name: Install client dependencies
      run: npm ci
      working-directory: ./client
    - name: Build server
      run: npm run build --if-present
      working-directory: ./server
    - name: Build client
      run: npm run build --if-present
      working-directory: ./client
