name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 19.x ]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install server dependencies
      run: npm ci
      working-directory: /home/ubuntu/SocialMedia/Cambiame/server
    - name: Install client dependencies
      run: npm ci
      working-directory: /home/ubuntu/SocialMedia/Cambiame/client
    - name: Build server
      run: npm run build --if-present
      working-directory: /home/ubuntu/SocialMedia/Cambiame/Cambiame/server
    - name: Build client
      run: npm run build --if-present
      working-directory: /home/ubuntu/SocialMedia/Cambiame/Cambiame/client
